# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('dim-ordered-raw-example', ['core', 'network', 'point-to-point', 'switchless'])
    obj.source = {
        'dim-ordered-raw-client.cc',
        'dim-ordered-raw-server.cc',
        'dim-ordered-raw-example.cc'
    }
    
